name: IPAbuyer Development Workflow

on:
  push:
    branches:
    - beta
  workflow_dispatch:


env:
  PROJECTCSPROJ: .\src\IPAbuyer.csproj

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore
      run: dotnet restore ${{ env.PROJECTCSPROJ }}

    - name: Decode and Install Certificate
      id: cert
      run: |
        $certBytes = [Convert]::FromBase64String($secrets.CERT_PFX_BASE64)
        $certPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "cert.pfx"
        [System.IO.File]::WriteAllBytes($certPath, $certBytes)

        $cert = Import-PfxCertificate -FilePath $certPath -CertStoreLocation Cert:\CurrentUser\My

        echo "THUMBPRINT=$($cert.Thumbprint)" >> $env:GITHUB_OUTPUT

    - name: Build
      run: |
        dotnet build ${{ env.PROJECTCSPROJ }} `
          -c Release /p:WindowsPackageType=MSIX `
          /p:GenerateAppxPackageOnBuild=true `
          /p:Platform=x64 `
          /p:AppxPackageSigningEnabled=true `
          /p:PackageCertificateThumbprint="${{ steps.cert.outputs.THUMBPRINT }}"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WinUI3-Package-x64
        path: |
          **\AppPackages\**\*.msix

    - name: Cleanup Certificate
      if: always()
      run: |
        $certPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "cert.pfx"
        if (Test-Path $certPath) {
          Remove-Item -Path $certPath -Force
        }

        $thumbprint = "${{ steps.cert.outputs.THUMBPRINT }}"
        if ($thumbprint) {
          Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.Thumbprint -eq $thumbprint } | Remove-Item -Force
        }
